spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  profiles:
    include:
      - db
      - kakao
      - sms
      - s3
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize : 10MB

logging:
  level:
    org:
      hibernate:
        type:
          description:
            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
